version: "3"
services:
  video-stream-api:
    image: video-stream-api
    depends_on:
      - video-stream-core
    links:
      - video-stream-core
  video-stream-conv-server:
    image: video-stream-conv-server
    depends_on:
      - video-stream-core
    links:
      - video-stream-core
  video-stream-conv-worker:
    image: video-stream-conv-worker
  video-stream-core:
    image: video-stream-core
    ports:
      - "9993:8080"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - video-stream-api
      - video-stream-conv-server
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"